import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import PomoDoroTimer from "./Timer/Pomodoro";
import AllTodos from "../app/todos/todoData";



const MainFont = Roboto({
  subsets: ["latin"],
  weight: "500",
});



export const metadata: Metadata = {
  title: `Focus-App ${timeLeft}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${MainFont.className} antialiased `}>
      <body className="grid grid-cols-9 gap-1 relative bg-main dark:bg-slate-800 text-text-color">
        <main className="col-start-1 col-end-7">{children}</main>
        <aside className="col-start-7 col-end-10 fixed">
          <PomoDoroTimer />

          <AllTodos />
        </aside>
      </body>
    </html>
  );
}
